nombre = input("ingresa nombre del alumno: ")
apellido = input("ingresa el apellido del alumno: ")
nota1 = int(input("ingresa la primer nota: "))
nota2 = int(input("ingresa la segundo nota: "))
nota3 = int(input("ingresa la tercer nota: "))
suma_de_notas = (nota1 + nota2 + nota3)
print("el promedio del alumno seria: ",(suma_de_notas/3))